export const STRINGS = {
    login: {
        welcomeBack: 'Welcome Back',
        subtitle: 'Log in to continue to BlogSpace',
        email: 'Email',
        password: 'Password',
        forgotPassword: 'Forgot password?',
        login: 'Log In',
        noAccount: "Don't have an account?",
        signup: 'Sign up',
    },

    signup: {
        title: 'BlogSpace',
        subtitle: 'Share your stories with the world',
        name: 'Name',
        username: "Username",
        email: 'Email',
        password: 'Password',
        confirmPassword: 'Confirm Password',
        createAccount: 'Create Account',
        or: 'or',
        google: 'Continue with Google',
        apple: 'Continue with Apple',
        alreadyAccount: 'Already have an account?',
        login: 'Log in',
        emailError: 'Please enter a valid email address',
    },
    home: {
        title: 'BlogSpace',
        allPosts: 'All Posts',
        following: 'Following',
    },
    addPost: {
        title: 'New Post',
        publish: 'Publish',
        postTitle: 'Post Title',
        content: 'Write your story...',
        status: 'Status',
        active: 'Active',
        inactive: 'Inactive',
        upload: 'Add Cover Image',
        uploadDesc: 'Tap to select image',
    },
    profile: {
        posts: 'Posts',
        followers: 'Followers',
        following: 'Following',
        follow: 'Follow',
        unfollow: 'Unfollow',
    },
    postDetail: {
        follow: 'Follow',
    },
    likes: {
        title: 'Liked by',
        peopleLiked: 'people liked this post',
        follow: 'Follow',
        following: 'Following',
    },
    followers: {
        title: 'Followers',
        follow: 'Follow',
        following: 'Following',
        you: 'You',
    },
    following: {
        title: 'Following',
        follow: 'Follow',
        following: 'Following',
    },
    comments: {
        title: 'Comments',
        placeholder: 'Add a comment...',
        reply: 'Reply',
    },
    setting: {
        title: 'Settings',
        logout: 'Logout',
        description: "Are you sure you want to logout?",
    }
};